# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "de4b14ec67e34726e9af9d1f91a499e2"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "Filter"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# read/write_products covers products, collections, and their metafields.
scopes = "read_products,write_products"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
